name: 'Release'
on:
  push:
      tags:
        - v* # Run only on version tags
jobs:
  push:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Set up build dir
        run: |
            mkdir -p build
      - name: run
        uses: cedrickring/golang-action@1.5.1
        with:
          args: CGO_ENABLED=0 go build -o build/envserver ./cmd/envserver
      - name: Build & Push Container
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BUILD_PATH: build
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "telliottio/envserver"
          TAG_NAME: ${{ steps.tagName.outputs.tag }}
          LATEST: "false"